'use strict';
/**
 * Browser runner — executes ERplorer "UI" steps (goto, fill, click,
 * expectText, expectVisible, expectUrl, wait) against a real Chromium
 * instance via Playwright, with:
 *   - full video recording (WebM, Playwright's native recorder —
 *     this is the DevTools-protocol-backed screencast under the hood)
 *   - per-step screenshots
 *   - console + page-error capture
 * All of it is logged into the Session so it becomes part of the
 * flow doc + RAG text.
 */

const path = require('path');
const fs = require('fs');
const { chromium } = require('playwright');

async function runUiSteps(session, steps, opts = {}) {
  const videoDir = path.join(session.dir, 'video');
  fs.mkdirSync(videoDir, { recursive: true });

  const browser = await chromium.launch({ headless: opts.headless !== false });
  const context = await browser.newContext({
    recordVideo: { dir: videoDir, size: { width: 1280, height: 800 } },
    viewport: { width: 1280, height: 800 }
  });
  const page = await context.newPage();

  page.on('console', msg => {
    session.logConsole({ level: msg.type(), text: msg.text() });
  });
  page.on('pageerror', err => {
    session.logConsole({ level: 'error', text: String(err) });
  });

  let response = null; // last API response object, for apiRequest steps done in-page context if needed

  try {
    for (const step of steps) {
      const { action, selector = '', value = '', url = '', expected = '' } = step;
      let status = 'ok';
      let error = null;
      let screenshot = null;

      try {
        switch (action) {
          case 'goto':
            await page.goto(url || value, { waitUntil: 'domcontentloaded', timeout: 30000 });
            break;
          case 'fill':
            await page.fill(selector, value, { timeout: 10000 });
            break;
          case 'click':
            await page.click(selector, { timeout: 10000 });
            break;
          case 'expectText': {
            const txt = await page.locator(selector).innerText({ timeout: 10000 });
            if (!txt.includes(expected || value)) throw new Error(`expected text "${expected || value}" not found, got "${txt}"`);
            break;
          }
          case 'expectVisible':
            await page.locator(selector).waitFor({ state: 'visible', timeout: 10000 });
            break;
          case 'expectUrl': {
            const cur = page.url();
            const re = new RegExp(url || value);
            if (!re.test(cur)) throw new Error(`expected URL matching /${url || value}/, got ${cur}`);
            break;
          }
          case 'wait':
            await page.waitForTimeout(Number(value) || 1000);
            break;
          default:
            status = 'skipped';
            error = `unsupported action: ${action}`;
        }
      } catch (e) {
        status = 'error';
        error = e.message;
      }

      // screenshot after every step (cheap, and priceless for debugging)
      try {
        const shotName = `${session.steps.length}_${action}.png`.replace(/[^\w.-]/g, '_');
        const shotPath = path.join(session.dir, 'screenshots', shotName);
        await page.screenshot({ path: shotPath });
        screenshot = path.relative(session.dir, shotPath);
      } catch (e) { /* ignore screenshot failure */ }

      session.logStep({ action, selector, value: value || url, status, error, screenshot });

      if (status === 'error' && opts.stopOnError) break;
    }
  } finally {
    await context.close(); // finalizes the WebM video file
    await browser.close();

    // Playwright writes video with an autogenerated name; find it and record path
    const files = fs.readdirSync(videoDir).filter(f => f.endsWith('.webm'));
    if (files.length) {
      session.setVideo(path.relative(session.dir, path.join(videoDir, files[0])));
    }
  }

  return { ok: session.steps.every(s => s.status !== 'error') };
}

module.exports = { runUiSteps };
